services:

    #
    # Form Types
    #
    elcodi.admin.banner.form_type.banner:
        class: %elcodi.admin.banner.form_type.banner.class%
        tags:
            - { name: form.type, alias: elcodi_admin_banner_form_type_banner }

    elcodi.admin.banner.form_type.banner_zone:
        class: %elcodi.admin.banner.form_type.banner_zone.class%
        tags:
            - { name: form.type, alias: elcodi_admin_banner_form_type_banner_zone }
