parameters:

    #
    # Pagination fields
    #
    elcodi.admin.banner.pagination.banner.fields:
        - id
        - name
        - description
        - url
        - position
        - enabled
    elcodi.admin.banner.pagination.banner_zone.fields:
        - id
        - name
        - code
        - height
        - width
