parameters:

    #
    # Entity classes
    #
    elcodi.admin.cartcoupon.form_type.order_coupon.class: Elcodi\Admin\CartCouponBundle\Form\Type\OrderCouponType
    elcodi.admin.cartcoupon.form_type.cart_coupon.class: Elcodi\Admin\CartCouponBundle\Form\Type\CartCouponType
