services:

    #
    # Form Types
    #
    elcodi.admin.cartcoupon.form_type.order_coupon:
        class: %elcodi.admin.cartcoupon.form_type.order_coupon.class%
        tags:
            - { name: form.type, alias: elcodi_admin_cartcoupon_form_type_order_coupon }

    elcodi.admin.cartcoupon.form_type.cart_coupon:
        class: %elcodi.admin.cartcoupon.form_type.cart_coupon.class%
        tags:
            - { name: form.type, alias: elcodi_admin_cartcoupon_form_type_cart_coupon }
