parameters:

    #
    # Pagination fields
    #
    elcodi.admin.newsletter.pagination.newsletter_subscription.fields:
        - id
        - email
        - hash
        - reason
        - createdAt
        - updatedAt
        - enabled
