services:

    #
    # Form Types
    #
    admin.user.form_type.login:
        class: %admin.user.form_type.login.class%
        arguments:
            router: @router
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_login }

    admin.user.form_type.register:
        class: %admin.user.form_type.register.class%
        arguments:
            customer_namespace: %elcodi.core.user.entity.customer.class%
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_register }

    admin.user.form_type.profile:
        class: %admin.user.form_type.profile.class%
        arguments:
            customer_namespace: %elcodi.core.user.entity.customer.class%
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_profile }

    admin.user.form_type.password_remember:
        class: %admin.user.form_type.password_remember.class%
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_password_remember }

    admin.user.form_type.password_recover:
        class: %admin.user.form_type.password_recover.class%
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_password_recover }

    admin.user.form_type.customer:
        class: %admin.user.form_type.customer.class%
        arguments:
            customer_factory: @elcodi.factory.customer
            language_factory: @elcodi.factory.language
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_customer }

    admin.user.form_type.admin_user:
        class: %admin.user.form_type.admin_user.class%
        arguments:
            admin_user_factory: @elcodi.factory.admin_user
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_admin_user }
