services:

    #
    # Form Types
    #
    elcodi.admin.configuration.form_type.configuration:
        class: %elcodi.admin.configuration.form_type.configuration.class%
        tags:
            - { name: form.type, alias: elcodi_admin_configuration_form_type_configuration }
