services:

    #
    # Form Types
    #
    elcodi.admin.media.form_type.image:
        class: %elcodi.admin.media.form_type.image.class%
        tags:
            - { name: form.type, alias: elcodi_admin_media_form_type_image }
