parameters:

    #
    # Entity classes
    #
    elcodi.admin.rule.form_type.rule.class: Elcodi\AdminRuleBundle\Form\Type\RuleType
    elcodi.admin.rule.form_type.rule_group.class: Elcodi\AdminRuleBundle\Form\Type\RuleGroupType
    elcodi.admin.rule.form_type.expression.class: Elcodi\AdminRuleBundle\Form\Type\ExpressionType
